/*
# IFITEO - Sistema de Geração Automática de Calendário Acadêmico

## Overview
This migration creates the complete database schema for the IFITEO academic calendar management system.
The system allows cadastring classes, subjects, teachers with availability, holidays/events,
and automatically generates the academic calendar respecting all constraints.

## New Tables

1. **periodos_academicos** — Academic periods (year, semester, start/end dates)
2. **horarios** — Time slots configurable (period of day, start/end, order)
3. **turmas** — Classes/groups (name, course, linked to academic period)
4. **disciplinas** — Subjects (name only; workload derived from class assignments)
5. **professores** — Teachers (name, email, phone)
6. **turma_disciplinas** — Assignments linking teacher + subject + class + number of classes needed
7. **professor_disponibilidade** — Teacher availability grid (day of week + time slot)
8. **feriados** — Holidays and blockings (date, description, type, scope)
9. **eventos** — Academic events (date range, time slot, description, blocks classes)
10. **aulas** — Scheduled classes generated by the algorithm (date, time slot, class, subject, teacher)
11. **configuracoes** — System settings (optimization priority, institution name)

## Security
- RLS enabled on all tables.
- Single-tenant, no-auth app: all policies use `TO anon, authenticated` with `USING (true)` / `WITH CHECK (true)`.
- The data is intentionally shared/public — no user isolation needed.
*/

-- ============================================================
-- 1. PERIODOS ACADÊMICOS
-- ============================================================
CREATE TABLE IF NOT EXISTS periodos_academicos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ano integer NOT NULL,
  semestre integer NOT NULL CHECK (semestre IN (1, 2)),
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE periodos_academicos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_periodos" ON periodos_academicos;
CREATE POLICY "anon_crud_periodos" ON periodos_academicos FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 2. HORÁRIOS (time slots)
-- ============================================================
CREATE TABLE IF NOT EXISTS horarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ordem integer NOT NULL,
  periodo text NOT NULL CHECK (periodo IN ('Manhã', 'Tarde', 'Noite')),
  hora_inicio text NOT NULL,
  hora_fim text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE horarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_horarios" ON horarios;
CREATE POLICY "anon_crud_horarios" ON horarios FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 3. TURMAS (classes)
-- ============================================================
CREATE TABLE IF NOT EXISTS turmas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  curso text NOT NULL,
  periodo_academico_id uuid REFERENCES periodos_academicos(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE turmas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_turmas" ON turmas;
CREATE POLICY "anon_crud_turmas" ON turmas FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 4. DISCIPLINAS (subjects)
-- ============================================================
CREATE TABLE IF NOT EXISTS disciplinas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE disciplinas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_disciplinas" ON disciplinas;
CREATE POLICY "anon_crud_disciplinas" ON disciplinas FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 5. PROFESSORES (teachers)
-- ============================================================
CREATE TABLE IF NOT EXISTS professores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  email text,
  telefone text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE professores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_professores" ON professores;
CREATE POLICY "anon_crud_professores" ON professores FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 6. TURMA_DISCIPLINAS (class-subject-teacher assignments)
-- ============================================================
CREATE TABLE IF NOT EXISTS turma_disciplinas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  turma_id uuid NOT NULL REFERENCES turmas(id) ON DELETE CASCADE,
  disciplina_id uuid NOT NULL REFERENCES disciplinas(id) ON DELETE CASCADE,
  professor_id uuid NOT NULL REFERENCES professores(id) ON DELETE CASCADE,
  num_aulas integer NOT NULL DEFAULT 2 CHECK (num_aulas > 0),
  created_at timestamptz DEFAULT now(),
  UNIQUE(turma_id, disciplina_id)
);

ALTER TABLE turma_disciplinas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_turma_disciplinas" ON turma_disciplinas;
CREATE POLICY "anon_crud_turma_disciplinas" ON turma_disciplinas FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 7. PROFESSOR_DISPONIBILIDADE (teacher availability)
-- ============================================================
CREATE TABLE IF NOT EXISTS professor_disponibilidade (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  professor_id uuid NOT NULL REFERENCES professores(id) ON DELETE CASCADE,
  dia_semana integer NOT NULL CHECK (dia_semana BETWEEN 0 AND 6),
  horario_id uuid NOT NULL REFERENCES horarios(id) ON DELETE CASCADE,
  UNIQUE(professor_id, dia_semana, horario_id)
);

ALTER TABLE professor_disponibilidade ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_prof_disp" ON professor_disponibilidade;
CREATE POLICY "anon_crud_prof_disp" ON professor_disponibilidade FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 8. FERIADOS (holidays / blockings)
-- ============================================================
CREATE TABLE IF NOT EXISTS feriados (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  data date NOT NULL,
  descricao text NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('Nacional', 'Estadual', 'Municipal', 'Institucional', 'Recesso', 'Paralisação', 'Outro')),
  abrangencia text NOT NULL DEFAULT 'Todas',
  turma_id uuid REFERENCES turmas(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE feriados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_feriados" ON feriados;
CREATE POLICY "anon_crud_feriados" ON feriados FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 9. EVENTOS (academic events)
-- ============================================================
CREATE TABLE IF NOT EXISTS eventos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  horario_id uuid REFERENCES horarios(id) ON DELETE SET NULL,
  descricao text,
  abrangencia text NOT NULL DEFAULT 'Todas',
  turma_id uuid REFERENCES turmas(id) ON DELETE CASCADE,
  bloqueia_aulas boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE eventos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_eventos" ON eventos;
CREATE POLICY "anon_crud_eventos" ON eventos FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 10. AULAS (scheduled classes — the generated calendar)
-- ============================================================
CREATE TABLE IF NOT EXISTS aulas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  data date NOT NULL,
  horario_id uuid NOT NULL REFERENCES horarios(id) ON DELETE CASCADE,
  turma_id uuid NOT NULL REFERENCES turmas(id) ON DELETE CASCADE,
  disciplina_id uuid NOT NULL REFERENCES disciplinas(id) ON DELETE CASCADE,
  professor_id uuid NOT NULL REFERENCES professores(id) ON DELETE CASCADE,
  turma_disciplina_id uuid NOT NULL REFERENCES turma_disciplinas(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(data, horario_id, turma_id)
);

CREATE INDEX IF NOT EXISTS idx_aulas_data ON aulas(data);
CREATE INDEX IF NOT EXISTS idx_aulas_turma ON aulas(turma_id);
CREATE INDEX IF NOT EXISTS idx_aulas_professor ON aulas(professor_id);

ALTER TABLE aulas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_aulas" ON aulas;
CREATE POLICY "anon_crud_aulas" ON aulas FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 11. CONFIGURAÇÕES (system settings)
-- ============================================================
CREATE TABLE IF NOT EXISTS configuracoes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome_instituicao text NOT NULL DEFAULT 'Instituto Arquidiocesano de Filosofia e Teologia São João Paulo II – IFITEO',
  prioridade_otimizacao text NOT NULL DEFAULT 'concentracao'
    CHECK (prioridade_otimizacao IN ('concentracao', 'menor_dias', 'disponibilidade', 'equilibrada')),
  aulas_consecutivas boolean NOT NULL DEFAULT true,
  multi_turma_mesmo_dia boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_crud_configuracoes" ON configuracoes;
CREATE POLICY "anon_crud_configuracoes" ON configuracoes FOR ALL
  TO anon, authenticated USING (true) WITH CHECK (true);

-- Insert default config if not exists
INSERT INTO configuracoes (nome_instituicao, prioridade_otimizacao, aulas_consecutivas, multi_turma_mesmo_dia)
SELECT 'Instituto Arquidiocesano de Filosofia e Teologia São João Paulo II – IFITEO', 'concentracao', true, true
WHERE NOT EXISTS (SELECT 1 FROM configuracoes);

-- Insert default horarios if not exists
INSERT INTO horarios (ordem, periodo, hora_inicio, hora_fim)
SELECT * FROM (VALUES
  (1, 'Manhã', '08h00', '09h40'),
  (2, 'Manhã', '10h00', '11h40'),
  (3, 'Tarde', '13h30', '15h10'),
  (4, 'Tarde', '15h30', '17h10')
) AS v(ordem, periodo, hora_inicio, hora_fim)
WHERE NOT EXISTS (SELECT 1 FROM horarios);